console.log("Avanish")
console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")

console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")

console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")

console.log("Avanish")
console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")

console.log("Avanish")
console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")
console.log("Avanish")
console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")
console.log("Avanish")
console.log("Changes are going")
console.log("Changes are going")
console.log("Changes are going")
